"""add clinic settings

Revision ID: 1c72084fac9c
Revises: 999215bea700
Create Date: 2026-07-20 18:13:21.636113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c72084fac9c'
down_revision: Union[str, Sequence[str], None] = '999215bea700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # CHECK constraints added by hand — autogenerate doesn't emit them.
    #  - id = 1        : the singleton guarantee (only one clinic).
    #  - hours sane    : 0..23, and close strictly after open.
    #  - slot positive : a non-positive slot would make no sense.
    op.create_table('clinic_settings',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('open_hour', sa.Integer(), server_default='9', nullable=False),
    sa.Column('close_hour', sa.Integer(), server_default='18', nullable=False),
    sa.Column('slot_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('timezone', sa.Text(), server_default='Asia/Kolkata', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='clinic_settings_singleton'),
    sa.CheckConstraint(
        'open_hour >= 0 AND open_hour <= 23 AND close_hour >= 1 AND close_hour <= 24 '
        'AND close_hour > open_hour',
        name='clinic_settings_hours',
    ),
    sa.CheckConstraint('slot_minutes > 0', name='clinic_settings_slot'),
    sa.PrimaryKeyConstraint('id')
    )
    # Seed the single row so the app always has settings to read. Columns left
    # to their server_defaults (09:00-18:00, 30-min, Asia/Kolkata).
    op.execute("INSERT INTO clinic_settings (id) VALUES (1)")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinic_settings')
    # ### end Alembic commands ###
