"""add item kind and consultation fee

The 15th migration (step 6.7 — Pricing). Splits the catalogue into treatments
and medicines, and gives each dentist a consultation fee.

Three things autogenerate got right and two it could not know about:

- `treatment_item.kind` is added NOT NULL with `server_default='treatment'`, so
  every row that existed before 6.7 **backfills as a treatment** in the same
  statement. No separate UPDATE pass is needed (contrast 6.6's
  `appointment.number`, which had no sensible default and needed
  add-nullable -> UPDATE -> SET NOT NULL).
- The old **unique** index on `treatment_item.name` becomes a plain index, and a
  composite UNIQUE on `(kind, name)` replaces it: the same word may name both a
  procedure and a medicine, but not two medicines.
- `staff_user.consultation_fee` is nullable — null means "not set", which is
  deliberately distinct from a 0.00 fee.

**Hand-added below (autogenerate emits neither):** the two CHECK constraints.
Both are named so `downgrade()` can drop them — the `999215bea700` trap, where
an unnamed constraint made a migration silently irreversible.

Revision ID: 36f29754ba8d
Revises: 6b93975ddf46
Create Date: 2026-07-30 08:33:08.434498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f29754ba8d'
down_revision: Union[str, Sequence[str], None] = '6b93975ddf46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_user', sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('treatment_item', sa.Column('kind', sa.Text(), server_default='treatment', nullable=False))
    op.drop_index(op.f('ix_treatment_item_name'), table_name='treatment_item')
    op.create_index(op.f('ix_treatment_item_name'), 'treatment_item', ['name'], unique=False)
    op.create_index(op.f('ix_treatment_item_kind'), 'treatment_item', ['kind'], unique=False)
    op.create_unique_constraint('uq_treatment_item_kind_name', 'treatment_item', ['kind', 'name'])
    # ### end Alembic commands ###

    # --- hand-added: autogenerate does not emit CHECK constraints ---
    # Pin the kind vocabulary at the DB. The app also validates it (Pydantic
    # Literal -> 422), but a typo'd kind written any other way would silently
    # hide items from every picker.
    op.create_check_constraint(
        "ck_treatment_item_kind",
        "treatment_item",
        "kind IN ('treatment', 'medicine')",
    )
    # A negative consultation fee is never meaningful. NULL stays legal — it
    # means "not set".
    op.create_check_constraint(
        "ck_staff_user_consultation_fee_non_negative",
        "staff_user",
        "consultation_fee IS NULL OR consultation_fee >= 0",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Hand-added CHECKs come off first — dropping a column with a constraint
    # still on it would fail.
    op.drop_constraint(
        "ck_staff_user_consultation_fee_non_negative", "staff_user", type_="check"
    )
    op.drop_constraint("ck_treatment_item_kind", "treatment_item", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_treatment_item_kind_name', 'treatment_item', type_='unique')
    op.drop_index(op.f('ix_treatment_item_kind'), table_name='treatment_item')
    op.drop_index(op.f('ix_treatment_item_name'), table_name='treatment_item')
    op.create_index(op.f('ix_treatment_item_name'), 'treatment_item', ['name'], unique=True)
    op.drop_column('treatment_item', 'kind')
    op.drop_column('staff_user', 'consultation_fee')
    # ### end Alembic commands ###
