"""add clinical record fields

The 16th migration (step 6.10 — the OPD clinical record). Adds the paper
out-patient card's fields to `visit`, guardian/address/recall to `patient`, and
a treatment `phase`.

**Four things hand-added on top of autogenerate** (it emits none of them):

1. **`CREATE SEQUENCE visit_number_seq`, before the column that defaults from
   it.** Autogenerate wrote `server_default=nextval('visit_number_seq')` from the
   model but has no idea the sequence has to exist first.
2. **The backfill is free here.** `nextval()` is *volatile*, so Postgres
   evaluates it per existing row when the NOT NULL column is added — unlike
   6.6's `appointment.number`, which had no default and needed the
   add-nullable -> UPDATE -> SET NOT NULL dance.
3. **The unique constraint is NAMED.** Autogenerate emitted
   `create_unique_constraint(None, ...)`, whose paired
   `drop_constraint(None, ...)` cannot drop anything — the exact trap from
   `999215bea700` that made a migration silently irreversible.
4. **The CHECK constraints** for BP ranges and the 1-4 phase.

`ALTER SEQUENCE ... OWNED BY` ties the sequence to the column so a downgrade
takes it away too, leaving no orphan.

Revision ID: 516032e0f8c0
Revises: 36f29754ba8d
Create Date: 2026-07-31 14:45:44.606683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '516032e0f8c0'
down_revision: Union[str, Sequence[str], None] = '36f29754ba8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # --- hand-added: the sequence must exist before the column defaults from it.
    # Starts at 1001 so the first readable id is V-1001, matching A-/L- (6.6).
    op.execute("CREATE SEQUENCE IF NOT EXISTS visit_number_seq START WITH 1001")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('guardian_name', sa.Text(), nullable=True))
    op.add_column('patient', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('patient', sa.Column('recall_due', sa.Date(), nullable=True))
    op.add_column('treatment', sa.Column('phase', sa.Integer(), nullable=True))
    op.add_column('visit', sa.Column('number', sa.Integer(), server_default=sa.text("nextval('visit_number_seq')"), nullable=False))
    op.add_column('visit', sa.Column('history_note', sa.Text(), nullable=True))
    op.add_column('visit', sa.Column('bp_systolic', sa.Integer(), nullable=True))
    op.add_column('visit', sa.Column('bp_diastolic', sa.Integer(), nullable=True))
    op.add_column('visit', sa.Column('habits', sa.Text(), nullable=True))
    op.add_column('visit', sa.Column('extra_oral', sa.Text(), nullable=True))
    op.add_column('visit', sa.Column('intra_oral', sa.Text(), nullable=True))
    op.add_column('visit', sa.Column('soft_tissues', sa.Text(), nullable=True))
    op.add_column('visit', sa.Column('hard_tissue', sa.Text(), nullable=True))
    op.add_column('visit', sa.Column('occlusion', sa.Text(), nullable=True))
    op.add_column('visit', sa.Column('missing_teeth', sa.Text(), nullable=True))
    op.add_column('visit', sa.Column('other_findings', sa.Text(), nullable=True))
    op.add_column('visit', sa.Column('investigations', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.add_column('visit', sa.Column('investigation_notes', sa.Text(), nullable=True))
    op.add_column('visit', sa.Column('provisional_diagnosis', sa.Text(), nullable=True))
    op.add_column('visit', sa.Column('differential_diagnosis', sa.Text(), nullable=True))
    op.add_column('visit', sa.Column('final_diagnosis', sa.Text(), nullable=True))
    op.add_column('visit', sa.Column('referred_to', sa.Text(), nullable=True))
    op.add_column('visit', sa.Column('referral_note', sa.Text(), nullable=True))
    # NAMED, so the downgrade can actually drop it (the 999215bea700 trap).
    op.create_unique_constraint('uq_visit_number', 'visit', ['number'])
    # ### end Alembic commands ###

    # --- hand-added: tie the sequence to the column, so dropping the column in
    # downgrade() takes the sequence with it rather than orphaning it.
    op.execute("ALTER SEQUENCE visit_number_seq OWNED BY visit.number")

    # --- hand-added: CHECK constraints (autogenerate emits none).
    # Wide bounds on purpose: a typo guard, not a clinical judgement.
    op.create_check_constraint(
        "ck_visit_bp_systolic_range",
        "visit",
        "bp_systolic IS NULL OR (bp_systolic BETWEEN 50 AND 300)",
    )
    op.create_check_constraint(
        "ck_visit_bp_diastolic_range",
        "visit",
        "bp_diastolic IS NULL OR (bp_diastolic BETWEEN 30 AND 200)",
    )
    op.create_check_constraint(
        "ck_treatment_phase_range",
        "treatment",
        "phase IS NULL OR (phase BETWEEN 1 AND 4)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Hand-added CHECKs come off first — a column can't be dropped while a
    # constraint still references it.
    op.drop_constraint("ck_treatment_phase_range", "treatment", type_="check")
    op.drop_constraint("ck_visit_bp_diastolic_range", "visit", type_="check")
    op.drop_constraint("ck_visit_bp_systolic_range", "visit", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_visit_number', 'visit', type_='unique')
    op.drop_column('visit', 'referral_note')
    op.drop_column('visit', 'referred_to')
    op.drop_column('visit', 'final_diagnosis')
    op.drop_column('visit', 'differential_diagnosis')
    op.drop_column('visit', 'provisional_diagnosis')
    op.drop_column('visit', 'investigation_notes')
    op.drop_column('visit', 'investigations')
    op.drop_column('visit', 'other_findings')
    op.drop_column('visit', 'missing_teeth')
    op.drop_column('visit', 'occlusion')
    op.drop_column('visit', 'hard_tissue')
    op.drop_column('visit', 'soft_tissues')
    op.drop_column('visit', 'intra_oral')
    op.drop_column('visit', 'extra_oral')
    op.drop_column('visit', 'habits')
    op.drop_column('visit', 'bp_diastolic')
    op.drop_column('visit', 'bp_systolic')
    op.drop_column('visit', 'history_note')
    op.drop_column('visit', 'number')
    op.drop_column('treatment', 'phase')
    op.drop_column('patient', 'recall_due')
    op.drop_column('patient', 'address')
    op.drop_column('patient', 'guardian_name')
    # ### end Alembic commands ###

    # The sequence is OWNED BY visit.number, so dropping that column already
    # removed it. Belt and braces in case the column was dropped some other way.
    op.execute("DROP SEQUENCE IF EXISTS visit_number_seq")
