"""add billing models

Revision ID: 800a7987a8ee
Revises: 1c72084fac9c
Create Date: 2026-07-21 05:29:35.535574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800a7987a8ee'
down_revision: Union[str, Sequence[str], None] = '1c72084fac9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted: money CHECK constraints
    # hand-added (autogenerate emits none). Named so they read clearly in \d and
    # are dropped with their table on downgrade. Money is Numeric, never float
    # (the 4.1 rule); these CHECKs stop a bad write path persisting negative money
    # or a discount larger than the subtotal.
    op.create_table('invoice',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.Text(), server_default='unpaid', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint(
        'subtotal >= 0 AND discount >= 0 AND total >= 0',
        name='invoice_amounts_nonneg',
    ),
    sa.CheckConstraint('discount <= subtotal', name='invoice_discount_le_subtotal'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')  # one invoice per visit (ERD §9)
    )
    op.create_index(op.f('ix_invoice_patient_id'), 'invoice', ['patient_id'], unique=False)
    op.create_table('invoice_line',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('treatment_item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('amount >= 0', name='invoice_line_amount_nonneg'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['treatment_item_id'], ['treatment_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_line_invoice_id'), 'invoice_line', ['invoice_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('paid_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='payment_amount_nonneg'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_invoice_id'), 'payment', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_invoice_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_invoice_line_invoice_id'), table_name='invoice_line')
    op.drop_table('invoice_line')
    op.drop_index(op.f('ix_invoice_patient_id'), table_name='invoice')
    op.drop_table('invoice')
    # ### end Alembic commands ###
