"""add treatment visit procedure_performed

Revision ID: 999215bea700
Revises: 73aeddd50693
Create Date: 2026-07-20 01:54:12.638577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999215bea700'
down_revision: Union[str, Sequence[str], None] = '73aeddd50693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('tooth_ref', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='in_progress', nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_patient_id'), 'treatment', ['patient_id'], unique=False)
    op.create_table('visit',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('treatment_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('dentist_id', sa.UUID(), nullable=True),
    sa.Column('visit_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('complaint', sa.Text(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['dentist_id'], ['staff_user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_patient_id'), 'visit', ['patient_id'], unique=False)
    op.create_index(op.f('ix_visit_treatment_id'), 'visit', ['treatment_id'], unique=False)
    op.create_table('procedure_performed',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('treatment_item_id', sa.UUID(), nullable=False),
    sa.Column('tooth_ref', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['treatment_item_id'], ['treatment_item.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedure_performed_visit_id'), 'procedure_performed', ['visit_id'], unique=False)
    # The FK deferred since 3.1: appointment.treatment_id was a bare nullable UUID
    # because `treatment` didn't exist until now. Named explicitly — autogenerate
    # emitted `None`, which upgrades fine (Postgres invents a name) but makes the
    # downgrade undroppable. Matches Postgres's own convention so the name is
    # what you'd expect in \d appointment.
    op.create_foreign_key(
        'appointment_treatment_id_fkey', 'appointment', 'treatment',
        ['treatment_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drops back to a bare nullable UUID column (the 3.1 shape) — the column
    # itself stays, only the constraint goes.
    op.drop_constraint(
        'appointment_treatment_id_fkey', 'appointment', type_='foreignkey'
    )
    op.drop_index(op.f('ix_procedure_performed_visit_id'), table_name='procedure_performed')
    op.drop_table('procedure_performed')
    op.drop_index(op.f('ix_visit_treatment_id'), table_name='visit')
    op.drop_index(op.f('ix_visit_patient_id'), table_name='visit')
    op.drop_table('visit')
    op.drop_index(op.f('ix_treatment_patient_id'), table_name='treatment')
    op.drop_table('treatment')
    # ### end Alembic commands ###
