"""add tooth condition chart

The 17th migration (step 6.11 — the dental chart / odontogram).

Autogenerate got this one right unaided, because it is a plain new table: the
foreign keys are unnamed but that is harmless here, since `DROP TABLE` in the
downgrade takes them with it — unlike the `999215bea700` trap, which was an
unnamed constraint added to an *existing* table and so could never be dropped.

**No CHECK on `condition`.** The vocabulary is enforced by a Pydantic `Literal`
in `schemas/chart.py`, matching how appointment status (3.5), payment mode (5.3)
and investigations (6.10) are handled — app-level, so the list can grow without
a migration. A dentist wanting to record "abrasion" next year should not need
a schema change.

**`ix_tooth_condition_current` is a PARTIAL index** (`WHERE superseded_at IS
NULL`). The chart read only ever asks for current rows, and superseded history
grows without bound, so indexing it too would be paying for rows nobody queries
that way.

Revision ID: d6425ed3d4b5
Revises: 516032e0f8c0
Create Date: 2026-07-31 15:06:13.662170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6425ed3d4b5'
down_revision: Union[str, Sequence[str], None] = '516032e0f8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tooth_condition',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('tooth', sa.Text(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('surfaces', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_visit_id', sa.UUID(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['staff_user.id'], ),
    sa.ForeignKeyConstraint(['recorded_visit_id'], ['visit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tooth_condition_current', 'tooth_condition', ['patient_id'], unique=False, postgresql_where=sa.text('superseded_at IS NULL'))
    op.create_index(op.f('ix_tooth_condition_patient_id'), 'tooth_condition', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tooth_condition_patient_id'), table_name='tooth_condition')
    op.drop_index('ix_tooth_condition_current', table_name='tooth_condition', postgresql_where=sa.text('superseded_at IS NULL'))
    op.drop_table('tooth_condition')
    # ### end Alembic commands ###
