"""add clinic identity fields

Revision ID: e8dbf0db4dec
Revises: 800a7987a8ee
Create Date: 2026-07-21 06:37:22.139373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8dbf0db4dec'
down_revision: Union[str, Sequence[str], None] = '800a7987a8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinic_settings', sa.Column('clinic_name', sa.Text(), server_default='Dental Clinic', nullable=False))
    op.add_column('clinic_settings', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('clinic_settings', sa.Column('phone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinic_settings', 'phone')
    op.drop_column('clinic_settings', 'address')
    op.drop_column('clinic_settings', 'clinic_name')
    # ### end Alembic commands ###
